# Generated by Django 2.0.5 on 2019-05-08 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190502_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.IntegerField(default=0, verbose_name='数量')),
                ('stock_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='进货时间')),
            ],
            options={
                'verbose_name': '进货信息',
                'verbose_name_plural': '进货信息',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='bid',
            field=models.FloatField(default=0, verbose_name='商品进价'),
        ),
        migrations.AddField(
            model_name='goodsstock',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品类目'),
        ),
    ]
