# Generated by Django 2.0.5 on 2019-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190508_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsstock',
            name='bid',
            field=models.FloatField(default=0, verbose_name='进价'),
        ),
    ]
