# Generated by Django 2.0.5 on 2019-05-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodsstock_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['pk'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='商品进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='市场价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='本店价格'),
        ),
        migrations.AlterField(
            model_name='goodsstock',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goodsstock',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品名'),
        ),
    ]
