# Generated by Django 2.0.5 on 2019-05-09 13:53

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190508_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['pk'], 'verbose_name': '首页轮播', 'verbose_name_plural': '首页轮播'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['pk'], 'verbose_name': '书籍信息', 'verbose_name_plural': '书籍信息'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '书籍类别', 'verbose_name_plural': '书籍类别'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'ordering': ['pk'], 'verbose_name': '商品轮播', 'verbose_name_plural': '商品轮播'},
        ),
        migrations.AlterModelOptions(
            name='hotsearchwords',
            options={'ordering': ['pk'], 'verbose_name': '热搜排行', 'verbose_name_plural': '热搜排行'},
        ),
        migrations.AlterModelOptions(
            name='indexad',
            options={'ordering': ['pk'], 'verbose_name': '首页广告', 'verbose_name_plural': '首页广告'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='ship_free',
        ),
        migrations.AddField(
            model_name='goods',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='书籍进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='书籍类目'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(max_length=500, verbose_name='书籍简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='书籍内容介绍'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=50, verbose_name='书籍唯一货号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='书籍销售量'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='书籍类目'),
        ),
        migrations.AlterField(
            model_name='goodsstock',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='indexad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='书籍类目'),
        ),
    ]
