# Generated by Django 2.0.5 on 2019-05-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190502_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='nonce_str',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='trade_no',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='是否发货'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='书籍'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='书籍数量'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_mount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='订单金额'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='书籍'),
        ),
    ]
