# Generated by Django 2.0.5 on 2019-05-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190501_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='书籍id', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='书籍'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(default='', help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
